load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "empty_problem",
    hdrs = [
        "empty_problem.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/status",
    ],
)
